Matrix Calculation in juypiter 

In [2]:
vector=[[1,2,3],[3,4,6],[4,6,7]]
print(vector)
print(type(vector))

[[1, 2, 3], [3, 4, 6], [4, 6, 7]]
<class 'list'>


In [3]:
vector1=[[3,4,5],[5,6,7],[7,8,9]]
print(vector+vector1)  
# Concatinating the vectors 

[[1, 2, 3], [3, 4, 6], [4, 6, 7], [3, 4, 5], [5, 6, 7], [7, 8, 9]]


In [4]:
import numpy as np
# Python library working for arrays
# popular module for vector calculation

In [5]:
a=np.array([[10,15]])
b=np.array([[20,9]])
print(a)
print(b)

[[10 15]]
[[20  9]]


In [7]:
print(type(a))
print(a)

<class 'numpy.ndarray'>
[[10 15]]


In [15]:
print(a[[0]]) #[[10,15]]
print(a[0])  #[10,15]

[[10 15]]
[10 15]


In [16]:
# Addition of Two Vectors
print(a+b)

[[30 24]]


In [19]:
print(a.T)
print((a+b).T)


[[10]
 [15]]
[[30]
 [24]]


In [20]:
print(a-b)

[[-10   6]]


In [22]:
print((a-b).T==a.T-b.T)

[[ True]
 [ True]]


In [28]:
#Matrix Multiplication
a=np.array([[1,2,3],[3,4,6],[4,6,7]])
b=np.array([[3,4,5],[5,6,7],[7,8,9]])
print(a,end=' =a\n')
print(b,end=' =b\n')
# \n for next line 
print(a*b)

[[1 2 3]
 [3 4 6]
 [4 6 7]] =a
[[3 4 5]
 [5 6 7]
 [7 8 9]] =b
[[ 3  8 15]
 [15 24 42]
 [28 48 63]]


In [29]:
print((a*b).T)

[[ 3 15 28]
 [ 8 24 48]
 [15 42 63]]


In [30]:
# Matrix Scalar Multiplication
a=4
print(a*b)


[[12 16 20]
 [20 24 28]
 [28 32 36]]


In [36]:
# Matrix Vector Multiplication
a=np.array([[3,4],[5,6]])
b=np.array([10,13])
print(np.dot(a,b))


[ 82 128]


In [38]:
# Transpose Of Matrix
print(a,end='=a\n')
print(a.T,end=' =aT\n')


[[3 4]
 [5 6]]=a
[[3 5]
 [4 6]] =aT


In [41]:
#Create a Identity Matrix

I1 =np.eye(2)
I2=np.eye(3)
I3=np.eye(4,5)
# The np.eye function in NumPy is used to create a 2-D array with ones on the diagonal and zeros elsewhere.
# The np.eye(N, M=None, k=0, dtype=float, order='C') function has the following parameters:

# N: The number of rows in the output matrix.

print(I1,end='=I1\n')
print(I2,end='=I2\n')
print(I3)

[[1. 0.]
 [0. 1.]]=I1
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]=I2
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [43]:
#Inverse a Matrix 
# Given a sqaure matric return a matrix ainv satisfying dot(a,ainv )=dot(ainv,a)=eye(a.shape[0])

a=np.array([1,2,3],[2,3,4],[3,4,5])
print(a,end='=a\n')
print(np.linalg.inv(a),end=' =|a|')

TypeError: array() takes from 1 to 2 positional arguments but 3 were given